# Generated by Django 4.0.4 on 2022-04-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='avatar',
            field=models.TextField(default='https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQSRpiKVmDu4KctY07T_FzEnYkdYFBCwoqU2NDlNc6HKej9jXHjZQ', verbose_name='Link to the photo'),
        ),
    ]
